/*
* generated by Xtext
*/
package com.mguidi.soa;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SOAUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.mguidi.soa.ui.internal.SOAActivator.getInstance().getInjector("com.mguidi.soa.SOA");
	}
	
}
