/*
 * generated by Xtext
 */
package com.mguidi.soa;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SOARuntimeModule extends com.mguidi.soa.AbstractSOARuntimeModule {

}
