/*
* generated by Xtext
*/
package com.mguidi.soa;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SOAStandaloneSetup extends SOAStandaloneSetupGenerated{

	public static void doSetup() {
		new SOAStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

