/*
 * generated by Xtext
 */
package com.mguidi.soa.validation

import org.eclipse.xtext.validation.Check
import com.mguidi.soa.soa.Model
import com.mguidi.soa.soa.SoaPackage
import com.mguidi.soa.soa.Entities

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class SOAValidator extends AbstractSOAValidator {

	@Check
	def void checkEntityNameIsUnique(Entities entity) {
		var model = (entity.eContainer as Model);
		
		for (Entities e: model.entities.filter(typeof(Entities))) {
			if (e != entity && e.name.equals(entity.name)) {
				error("Entity and Enum names have to be unique", SoaPackage.Literals.ENTITIES__NAME);
					return;
			}	
		}
	}
	
}
