/*
* generated by Xtext
*/
package com.mguidi.soa.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.mguidi.soa.services.SOAGrammarAccess;

public class SOAParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SOAGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.mguidi.soa.parser.antlr.internal.InternalSOAParser createParser(XtextTokenStream stream) {
		return new com.mguidi.soa.parser.antlr.internal.InternalSOAParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Architecture";
	}
	
	public SOAGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SOAGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
