/**
 * generated by Xtext
 */
package com.mguidi.soa.ui.contentassist;

import com.mguidi.soa.ui.contentassist.AbstractSOAProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class SOAProposalProvider extends AbstractSOAProposalProvider {
}
