/*
 * generated by Xtext
 */
package com.mguidi.soa.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SOAUiModule extends com.mguidi.soa.ui.AbstractSOAUiModule {
	public SOAUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
