/*
 * generated by Xtext
 */
package com.mguidi.soa.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractSOAValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.mguidi.soa.soa.SoaPackage.eINSTANCE);
		return result;
	}
}
