/*
 * generated by Xtext
 */
package com.mguidi.soa.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.mguidi.soa.ui.internal.SOAActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SOAExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SOAActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SOAActivator.getInstance().getInjector(SOAActivator.COM_MGUIDI_SOA_SOA);
	}
	
}
